# Generated by Django 4.0.1 on 2022-01-15 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Immobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('rooms', models.IntegerField()),
                ('size', models.FloatField()),
                ('street', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('S', 'Sale'), ('R', 'Rent')], max_length=1)),
                ('type_immobile', models.CharField(choices=[('A', 'Apartment'), ('H', 'Home')], max_length=1)),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='innerpages.city')),
                ('images', models.ManyToManyField(to='innerpages.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('S', 'Scheduled'), ('F', 'Finished'), ('C', 'Canceled')], default='A', max_length=1)),
                ('immobile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='innerpages.immobile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='immobile',
            name='times',
            field=models.ManyToManyField(to='innerpages.Time'),
        ),
        migrations.AddField(
            model_name='immobile',
            name='visiting_days',
            field=models.ManyToManyField(to='innerpages.VisitingDays'),
        ),
    ]
